name: Package Preview

on:
  pull_request:
  push:
    branches:
      - nitro-modules
      - nitro-modules-merged

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #  ref: refs/pull/${{ github.event.number }}/merge

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - run: corepack enable

      - run: yarn install --immutable

      - run: yarn specs
        working-directory: packages/react-native-activity-kit

      - run: yarn pkg-pr-new publish './packages/*'